#Include all the file needed for project
INC += -I ./application
INC += -I ./application/libs
INC += -I ./application/apps

VPATH += ./application
VPATH += ./application/libs
VPATH += ./application/apps

#SOURCES += ./application/main_dac.c
#SOURCES += ./application/main_example.c
#SOURCES += ./application/main.c
SOURCES += ./application/main_pwm_example.c


SOURCES += ./application/libs/cli.c
SOURCES += ./application/apps/app_cli.c
SOURCES += ./application/apps/app_adc.c
SOURCES += ./application/apps/app_pwm.c














